import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${rubik.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <h1 className="text-4xl font-bold">Dojo Help Desk</h1>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
